# spring configuration
spring:
   application:
      name: myweb

   mvc:
      view:
         prefix: /WEB-INF/views/
         suffix: .jsp
         
# server configuration
server:
   port: 8089
   servlet:
      context-patch: /
      encoding: 
         charset: utf-8
         enabled: true